[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''
[build]
  publish = "dist"
  command = "ng build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
